---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-openshift-route-service
  namespace: keptn
  labels:
    "app": "keptn"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-secuirtycontextconstraints
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - get
      - update
    resourceNames:
      - privileged
      - anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-secuirtycontextconstraints
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-secuirtycontextconstraints
subjects:
  - kind: ServiceAccount
    name: keptn-openshift-route-service
    namespace: keptn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-route-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: openshift-route-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: develop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openshift-route-service
      app.kubernetes.io/instance: keptn
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openshift-route-service
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: develop
    spec:
      serviceAccountName: keptn-openshift-route-service
      containers:
      - name: openshift-route-service
        image: keptn/openshift-route-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: distributor
        image: keptn/distributor:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.internal.event.project.create'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: openshift-route-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: openshift-route-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
spec:
  ports:
  - name: cloudevents
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: openshift-route-service
    app.kubernetes.io/instance: keptn
